### ISSUE TITLE
Infinite loop in calculate_bound

### ISSUE THREAD

**Issue by basveeling** [geifmany/selective_deep_learning#1]
Hi Yonatan,

We spoke briefly during NIPS at your poster. I've been trying to incorporate your code into an evaluation scheme, but noticed that the function would sometimes not converge to a bound. I think I've narrowed it down to the following lines, where sometimes erm=1.0, and the function keeps evaluating the funcval at b=1.

Can we fix this with a simple check as follows?
```
    while abs(funcval) > precision:
        if a == 1.0 and c == 1.0:
            b = 1.0
            break
        elif funcval > 0:
            ...
```
```
def calculate_bound(delta, m, erm):
    # This function is a solver for the inverse of binomial CDF based on binary search.
    precision = 1e-7

    def func(b):
        return (-1 * delta) + scipy.stats.binom.cdf(int(m * erm), m, b)

    a = erm  # start binary search from the empirical risk
    c = 1  # the upper bound is 1
    b = (a + c) / 2  # mid point
    funcval = func(b)
    while abs(funcval) > precision:
        if funcval > 0:
            a = b
        else:
            c = b
        b = (a + c) / 2
        funcval = func(b)
    return b
```

**Comment by geifmany** [comment]
It looks like this can happened and you correction is needed.
Getting a bound with very low r^* and low delta is sometimes not attainable (see footnote 1 on page 3).
Let me know if it fixes this issue
Thanks
