### ISSUE TITLE
Could you share the code for plotting the risk-coverage curve in the paper

### ISSUE THREAD

**Issue by lixinsu** [geifmany/selective_deep_learning#3]
My email is sulixinict@gmaill.com. Thanks

**Comment by RussellXie7** [comment]
Hi Yonatan,

I have same request, and I am wondering if you are still maintaining this repository. Greatly appreciate it if you could update this repository with the code for plotting the risk-coverage curve. It seems a little bit ambiguous in the paper about how exactly it was implemented.

This would be very helpful to our current research. 

Thank you!

Best,

**Comment by geifmany** [comment]
Please see the code in this repo for how to draw a risk coverage curve.
https://github.com/geifmany/uncertainty_ICLR <https://github.com/geifmany/uncertainty_ICLR>
In utils.uncertainty_tools
